/**/


#define STD_AST_NODE_NUM_CHILDREN    64

enum AST_NODE_TYPE {
    AST_PROGRAM,
    AST_STATEMENT,
    AST_STATEMENT_LIST,
    AST_STATEMENT_BLOCK,
    AST_EXPRESSION,

    AST_ARGUMENTS,
    AST_ARGUMENT,

    AST_TYPE,
    AST_WRAPPED_TYPE,
    AST_TYPE_IDENTIFIER,
    AST_IDENTIFIER,
    AST_LITERAL,
    AST_CALLABLE,

    AST_IF_STATEMENT,
    AST_WHILE_STATEMENT,
    AST_FOR_STATEMENT,
    AST_ELSE_STATEMENT,
    AST_ELSE_IF_STATEMENT,
    AST_RETURN_STATEMENT,
    AST_DEFINE_STATEMENT,
    AST_ASSIGNMENT_STATEMENT,

    AST_BINARY_OPERATOR,
    AST_UNARY_OPERATOR,

} AST_NODE_TYPE;

struct AST_NODE {

    enum AST_NODE_TYPE type;
    struct Token * token;

    struct AST_NODE * children[STD_AST_NODE_NUM_CHILDREN];
    int max_num_children;
    int num_children;

} AST_NODE;
