
<type-wrapper> ::=
    | array
    | address

<type-specifier> ::=
    | char
    | string
    | int
    | float
    | double
    | struct
    | enum
    | callable
    | type
    | address
    | bool

<type> ::=
    | <type-specifier>
    | <type-wrapper> <type-specifier>
    | "[" <type-specifier> "]"
    
    // this will have to be thoroughly validated
    // during parsing, as many false-positives could arise
    // such as: [ address int array int]
    // which is nonsensical

    | "[" (<type-wrapper> <type-specifier>)* "]"
    
<assignment-operator> ::=
    | =
    | *=
    | /=
    | %=
    | +=
    | -=

<unary-operator> ::=
    | !
    | -


<stmt> ::= 
    | "if" "(" <expr> ")" <stmt> ("else" <stmt>)?
    | "for" "(" <expr-stmt> <expr>? ";" <expr>? ")" <stmt> 
    | "while" "(" <expr> ")" <stmt>
    | "continue" ";"
    | "break" ";"
    | "return" <expr>? ";"
    | "{" <stmt>* "}"
    | <expr> ";"

